#!/bin/sh
# Refresh source code
composer install  #--no-interaction
composer dump-autoload --optimize

# Clear caches
php bin/console cache:clear --env=dev --no-warmup
php bin/console cache:clear --env=prod --no-warmup --no-debug

# Update database schema
php bin/console doctrine:schema:update --force

# Migrate database
# php bin/console --no-interaction doctrine:migrations:migrate

# Add data fixtures
# php bin/console doctrine:fixtures:load --append --env=dev --em=default
