version: '3'

services:
    httpd:
        image: atdock/httpd:2.4
        container_name: apicore_httpd
        links:
            - php
        volumes:
            - ./.docker/httpd/default.conf:/usr/local/apache2/conf.d/default.conf
            - app-sync:/usr/local/apache2/htdocs:rw
        ports:
            - "8001:80"

    php:
        image: atdock/php:7.1
        container_name: apicore_php
        depends_on:
            - mysql
        volumes:
            - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - app-sync:/var/www:rw

    mysql:
        image: atdock/mysql:5.7
        container_name: apicore_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: apicore
            MYSQL_USER: apicore
            MYSQL_PASSWORD: apicore
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql:rw

volumes:
  app-sync:
    external: true