api_v1:
    resource: "@AppBundle/Resources/config/routing/api_v1.yml"
    prefix: /api/v1

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/v1/login_check

api_doc:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

homepage:
    path: /
    methods: GET
    defaults: { _controller: AppBundle:Default:index }
