# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth_login:
            pattern:  ^/auth/v1/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /auth/v1/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        user:
            pattern:   ^/api/v1/user
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - auth.jwt_token_authenticator

        main:
            pattern: ^/
            anonymous: ~
            logout: true
            logout_on_user_change: true

    access_control:
        - { path: ^/auth/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/v1,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/v1,        roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [ POST ] }
        - { path: ^/api,           roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN