AppBundle\Entity\User:
    exclusion_policy: ALL
    virtual_properties:
        getId:
            since_version: 1.0
            groups: [userDetail, userList]
        getEmail:
            since_version: 1.0
            groups: [userDetail, userList]
        getPhone:
            since_version: 1.0
            groups: [userDetail, userList]
        getStatus:
            since_version: 1.0
            groups: [userDetail, userList]
        isEnabled:
            serialized_name: enabled
            since_version: 1.0
            groups: [userDetail]
        getCreatedDate:
            since_version: 1.0
            groups: [userDetail, userList]
        getUpdatedDate:
            since_version: 1.0
            groups: [userDetail, userList]
