services:
    # Handler
    jms_serializer.form_error_handler:
        class: AppBundle\Serializer\Handler\FormErrorHandler
        arguments: ['@translator']
        tags:
          - {name: jms_serializer.subscribing_handler}
