AppBundle\Pagination\PaginatedCollection:
    exclusion_policy: ALL
    virtual_properties:
        getItems:
            since_version: 1.0
            groups: [paginated]
        getTotal:
            since_version: 1.0
            groups: [paginated]
        getCount:
            since_version: 1.0
            groups: [paginated]
        getLinks:
            since_version: 1.0
            groups: [paginated]